"""Recurrent v2 collection, V-trace learning, evaluation and checkpointing."""

from .checkpointing import (
    ActorSupervisorState,
    EvaluationGateState,
    TrainingState,
    actor_supervisor_state_from_metadata,
    checkpoint_summary,
    evaluation_gate_state_from_metadata,
    initialize_model_from_checkpoint,
    load_training_checkpoint,
    preflight_model_initialization,
    preflight_training_checkpoint,
    save_training_checkpoint,
)
from .collector import (
    CollectedEpisode,
    CollectionProtocolError,
    EpisodeMetrics,
    GroundedCollector,
)
from .config import (
    CONFIG_VERSION,
    CurriculumConfig,
    DiagnosticsConfig,
    EnvironmentConfig,
    EpisodicLearningConfig,
    ModelConfig,
    OptimizationConfig,
    RolloutConfig,
    RuntimeConfig,
    TrainingConfig,
    TransactionLearningConfig,
    load_training_config,
    training_config_from_mapping,
)
from .episode_replay import (
    BoundaryOutcome,
    BoundedEpisodicReplay,
    CompletedEpisode,
    EpisodeCompletion,
    EpisodeDecisionStep,
    HorizonTargets,
    ReplaySequence,
    backfill_completed_episode,
)
from .factory import (
    TrainingResources,
    build_backend,
    build_training_resources,
    resolve_device,
    seed_everything,
)
from .learner import LearnerMetrics, VTraceLearner
from .pipeline import ActorLearnerPipeline
from .runtime import (
    evaluate_policy,
    exploration_epsilon,
    inspect_baseline,
    run_training,
    summarize_evaluation,
)
from .transaction import (
    BoundedTransactionReplay,
    FactualTransactionPolicyTarget,
    ObservedTransactionPair,
    TransactionEffect,
    TransactionOutcome,
    TransactionPolicyTarget,
    TransactionStep,
    TransactionTrace,
    backfill_factual_monte_carlo_returns,
    factual_transaction_policy_targets,
    observed_outcome_pairs,
)

__all__ = [
    "CONFIG_VERSION",
    "ActorLearnerPipeline",
    "ActorSupervisorState",
    "BoundaryOutcome",
    "BoundedEpisodicReplay",
    "BoundedTransactionReplay",
    "CollectedEpisode",
    "CollectionProtocolError",
    "CompletedEpisode",
    "CurriculumConfig",
    "DiagnosticsConfig",
    "EnvironmentConfig",
    "EpisodeCompletion",
    "EpisodeDecisionStep",
    "EpisodeMetrics",
    "EpisodicLearningConfig",
    "EvaluationGateState",
    "FactualTransactionPolicyTarget",
    "GroundedCollector",
    "HorizonTargets",
    "LearnerMetrics",
    "ModelConfig",
    "ObservedTransactionPair",
    "OptimizationConfig",
    "ReplaySequence",
    "RolloutConfig",
    "RuntimeConfig",
    "TrainingConfig",
    "TrainingResources",
    "TrainingState",
    "TransactionEffect",
    "TransactionLearningConfig",
    "TransactionOutcome",
    "TransactionPolicyTarget",
    "TransactionStep",
    "TransactionTrace",
    "VTraceLearner",
    "actor_supervisor_state_from_metadata",
    "backfill_completed_episode",
    "backfill_factual_monte_carlo_returns",
    "build_backend",
    "build_training_resources",
    "checkpoint_summary",
    "evaluate_policy",
    "evaluation_gate_state_from_metadata",
    "exploration_epsilon",
    "factual_transaction_policy_targets",
    "initialize_model_from_checkpoint",
    "inspect_baseline",
    "load_training_checkpoint",
    "load_training_config",
    "observed_outcome_pairs",
    "preflight_model_initialization",
    "preflight_training_checkpoint",
    "resolve_device",
    "run_training",
    "save_training_checkpoint",
    "seed_everything",
    "summarize_evaluation",
    "training_config_from_mapping",
]
