"""Compatibility contracts for the large RL-module decomposition.

These checks intentionally live outside the private implementation modules.
They protect the historical import/type homes, checkpoint key surface, and the
ordering contracts consumed by replay data and trained policies.
"""

from __future__ import annotations

import hashlib
from typing import Any

import torch

from muzero.sts2_env import muzero_model, token_memory
from muzero.sts2_env.muzero_model import MuZeroNetwork
from sts2_env import observation_v3
from sts2_env._sim_translate import translate_to_bridge_shape


def test_compatibility_facades_keep_public_symbols_and_historical_type_homes() -> None:
    from muzero.sts2_env.muzero_model import ActionRolloutPlannerOutput
    from muzero.sts2_env.token_memory import (
        EntityTokenEmbedder,
        TokenDynamicsNetwork,
        TokenFutureWorldBankHead,
        TokenLatentProjector,
        TokenMemoryEncoder,
        TokenMemoryEncoderOutput,
        TokenPredictionNetwork,
        TokenTransitionSurfaceHead,
    )
    from sts2_env._sim_translate import SelfInflictedHpTracker, sim_kind_to_bridge_kind
    from sts2_env.combat_env import CombatSandboxEnv, CurriculumTracker, get_curriculum_tracker
    from sts2_env.env_v2 import SlayTheSpire2EnvV2
    from sts2_env.observation_v3 import ObservationEncoderV3, WorldTokenObservationEncoder

    assert ObservationEncoderV3 is WorldTokenObservationEncoder
    expected_type_homes = {
        WorldTokenObservationEncoder: "sts2_env.observation_v3",
        CombatSandboxEnv: "sts2_env.combat_env",
        CurriculumTracker: "sts2_env.combat_env",
        SlayTheSpire2EnvV2: "sts2_env.env_v2",
        SelfInflictedHpTracker: "sts2_env._sim_translate",
        EntityTokenEmbedder: "muzero.sts2_env.token_memory",
        TokenDynamicsNetwork: "muzero.sts2_env.token_memory",
        TokenFutureWorldBankHead: "muzero.sts2_env.token_memory",
        TokenLatentProjector: "muzero.sts2_env.token_memory",
        TokenMemoryEncoder: "muzero.sts2_env.token_memory",
        TokenMemoryEncoderOutput: "muzero.sts2_env.token_memory",
        TokenPredictionNetwork: "muzero.sts2_env.token_memory",
        TokenTransitionSurfaceHead: "muzero.sts2_env.token_memory",
        ActionRolloutPlannerOutput: "muzero.sts2_env.muzero_model",
        MuZeroNetwork: "muzero.sts2_env.muzero_model",
    }
    for symbol, expected_module in expected_type_homes.items():
        assert symbol.__module__ == expected_module

    # Functions that used to be defined in the facades remain resolvable from
    # their old pickle/introspection homes too.
    assert get_curriculum_tracker.__module__ == "sts2_env.combat_env"
    assert sim_kind_to_bridge_kind.__module__ == "sts2_env._sim_translate"
    assert muzero_model.scalar_to_support.__module__ == "muzero.sts2_env.muzero_model"
    assert token_memory.build_memory_slot_bank_ids.__module__ == "muzero.sts2_env.token_memory"

    # Representative historically importable constants/helpers guard against
    # an over-aggressive facade cleanup silently breaking out-of-tree callers.
    assert {
        "DEFAULT_EFFECT_PROFILE",
        "MAX_HISTORY_TOKENS",
        "OWNER_HAND",
        "TOKEN_TYPES",
        "_CARD_KEYWORD_BUCKETS",
        "_resolve_potion_effect",
    } <= set(observation_v3.__all__)
    assert {
        "CrossAttentionBlock",
        "MAX_WORLD_TOKENS",
        "TokenMemoryEncoder",
        "build_zone_transport_prior",
    } <= set(token_memory.__all__)
    assert {
        "DEFAULT_ACTION_ROLLOUT_BUCKETS",
        "MuZeroNetwork",
        "SEMANTIC_ROLLOUT_FEAT_DIM",
        "scalar_to_support",
    } <= set(muzero_model.__all__)


def _small_token_network() -> MuZeroNetwork:
    return MuZeroNetwork(
        obs_mode="token_v3",
        model_arch="token_memory_v1",
        action_embed_dim=8,
        token_d_model=16,
        token_n_heads=2,
        token_ffn_dim=32,
        token_world_layers=1,
        token_local_layers=1,
        token_decoder_layers=1,
        token_candidate_set_layers=0,
        token_memory_slots=8,
        token_world_bank_top_k=5,
        token_bank_token_slots=1,
    )


def test_token_muzero_checkpoint_surface_matches_pre_split_golden() -> None:
    torch.manual_seed(123)
    network = _small_token_network()
    state = network.state_dict()
    surface = "\n".join(f"{key}:{tuple(value.shape)}" for key, value in state.items())

    # Generated by the pre-split MuZeroNetwork with the constructor above.
    assert len(state) == 1803
    assert hashlib.sha256(surface.encode()).hexdigest() == (
        "ce8da0e51b4d3038873c0daa424905e95f383b8d8984e7955626a495f806857a"
    )
    assert not any("_muzero_action_rollout" in key or "_token_memory_" in key for key in state)

    clone = _small_token_network()
    incompatible = clone.load_state_dict(state, strict=True)
    assert incompatible.missing_keys == []
    assert incompatible.unexpected_keys == []


def _ordering_fixture() -> tuple[dict[str, Any], list[dict[str, Any]]]:
    card = {
        "id": "CARD.STRIKE",
        "title": "Strike",
        "type": "Attack",
        "cost": 1,
        "target": "SingleEnemy",
        "damage": 6,
        "semantic_tags": ["attack"],
    }
    observation = {
        "phase": "combat",
        "decision_domain": "combat",
        "player": {
            "hp": 52,
            "max_hp": 80,
            "block": 5,
            "gold": 99,
            "deck_cards": [card],
            "relics": [{"id": "RELIC.ANCHOR", "title": "Anchor"}],
            "potions": [{"id": "POTION.FIRE", "title": "Fire Potion"}],
        },
        "combat": {
            "in_progress": True,
            "energy": 3,
            "max_energy": 3,
            "hand": [card],
            "draw_pile": {"cards": [card]},
            "discard_pile": {"cards": []},
            "exhaust_pile": {"cards": []},
            "play_pile": {"cards": []},
            "enemies": [
                {
                    "name": "Jaw Worm",
                    "model_id": "MONSTER.JAW_WORM",
                    "combat_id": 7,
                    "current_hp": 33,
                    "max_hp": 40,
                    "block": 0,
                    "powers": [],
                    "intent": {
                        "intent_type": "attack",
                        "total_damage": 9,
                        "damage_per_hit": 9,
                        "repeats": 1,
                    },
                }
            ],
        },
        "run": {"floor": 2, "act": 1},
    }
    actions = [
        {
            "action_id": "play:0:7",
            "kind": "play_card",
            "card": card,
            "target": {"combat_id": 7, "name": "Jaw Worm"},
        },
        {"action_id": "end_turn", "kind": "end_turn"},
    ]
    return observation, actions


def test_world_and_candidate_token_order_matches_pre_split_golden() -> None:
    observation, actions = _ordering_fixture()
    encoded = observation_v3.WorldTokenObservationEncoder(use_text=False).encode(observation, actions)
    active_world_count = int(encoded["world_token_mask"].sum())
    world_types = [
        observation_v3.TOKEN_TYPES[int(type_id)]
        for type_id in encoded["world_token_type_ids"][:active_world_count]
    ]

    assert world_types[:14] == [
        "CLS_WORLD",
        "CLS_COMBAT",
        "CLS_BUILD",
        "CLS_ROUTE",
        "PLAYER_SURVIVAL",
        "RESOURCE_BUDGET",
        "THREAT_SUMMARY",
        "OBJECTIVE_CONTEXT",
        "RUN_CONTEXT",
        "HAND_CARD",
        "DECK_CARD",
        "DRAW_PREVIEW_CARD",
        "ENEMY_CORE",
        "ENEMY_INTENT",
    ]
    assert world_types[14:34] == ["HISTORY_STEP_DETAIL"] * 20
    assert world_types[34:42] == ["HISTORY_TURN_SUMMARY"] * 8
    assert [
        observation_v3.TOKEN_TYPES[int(type_id)]
        for type_id in encoded["candidate_query_type_ids"][:2]
    ] == ["COMBAT_CANDIDATE", "BUILD_CANDIDATE"]

    first_local_types = [
        observation_v3.TOKEN_TYPES[int(type_id)]
        for type_id, active in zip(
            encoded["candidate_local_type_ids"][0],
            encoded["candidate_local_masks"][0],
            strict=True,
        )
        if active
    ]
    assert first_local_types == [
        "SOURCE_CARD_LOCAL",
        "TARGET_LOCAL",
        "ENEMY_INTENT",
        "TARGET_REACTION_LOCAL",
        "PLAYER_STATE_LOCAL",
        "ENERGY_CONTEXT_LOCAL",
        "ENERGY_BUDGET_LOCAL",
        "CYCLE_PLAN_LOCAL",
        "DRAW_CONTEXT_LOCAL",
        "DISCARD_CONTEXT_LOCAL",
        "EXHAUST_CONTEXT_LOCAL",
        "PLAY_PILE_CONTEXT_LOCAL",
        "DRAW_BINDING_LOCAL",
        "DISCARD_BINDING_LOCAL",
        "DRAW_PREVIEW_CARD",
        "RELIC_TRIGGER_LOCAL",
        "POTION_OPTION_LOCAL",
        "RELIC_POTION_GRAPH_LOCAL",
    ]


def test_sim_translation_preserves_legal_action_order_and_ids() -> None:
    raw_actions = [
        {"action": "play_card", "card_index": 0, "target_id": 7},
        {"action": "use_potion", "slot": 0, "target_id": 7},
        {"action": "end_turn"},
    ]
    translated = translate_to_bridge_shape(
        {
            "state_type": "combat",
            "battle": {
                "player": {
                    "current_hp": 44,
                    "max_hp": 80,
                    "hand": [{"index": 0, "id": "CARD.STRIKE", "name": "Strike"}],
                    "potions": [{"slot": 0, "id": "POTION.FIRE", "name": "Fire Potion"}],
                },
                "enemies": [
                    {
                        "combat_id": 7,
                        "name": "Jaw Worm",
                        "current_hp": 33,
                        "max_hp": 40,
                    }
                ],
            },
            "legal_actions": raw_actions,
        },
        episode_id="compatibility-test",
    )["available_actions"]

    assert [action["idx"] for action in translated] == [0, 1, 2]
    assert [action["action_index"] for action in translated] == [0, 1, 2]
    assert [action["kind"] for action in translated] == ["play_card", "use_potion", "end_turn"]
    assert [action["action_id"] for action in translated] == [
        "sim:play_card:card_index=0:target_id=7",
        "sim:use_potion:slot=0:target_id=7",
        "sim:end_turn",
    ]
    assert [action["_sim_raw"] for action in translated] == raw_actions
